apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-web-app
  namespace: workloads
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: java-web-app
spec:
  params:
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: ajitkadari
  - name: gitops_repository_name
    value: java-web-app
  - name: gitops_sub_path
    value: config/dev-ns/java-web-app
  - name: gitops_ssh_secret
    value: "git-secret"
  - name: gitops_commit_branch
    value: "dev"
  - name: gitops_user_name
    value: "SupplyChain@TAP"
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/ajitkadari/java-web-app.git
      ref:
        branch: master
